import type { z } from 'zod'
import type {
  GenerateCoverBodySchema,
  SuggestCoverPromptBodySchema,
  UploadCoverBodySchema,
} from '@shared/contracts'
import { request } from './http'

/**
 * This module provides the endpoints for a book's cover image. A cover can
 * be suggested and generated by AI, replaced with an uploaded image, or
 * removed entirely.
 */

type SuggestCoverPromptRequest = z.infer<typeof SuggestCoverPromptBodySchema>
type GenerateCoverRequest = z.infer<typeof GenerateCoverBodySchema>
type UploadCoverRequest = z.infer<typeof UploadCoverBodySchema>

/** The cover art prompt the AI suggests from a book's title and topic. */
export interface SuggestCoverPromptResponse {
  prompt: string
}

/** A cover generation task that has just started, tracked by the background task stream. */
export interface CoverGenerationTask {
  taskId: string
}

/** Ask the AI to suggest a cover art prompt from a book's title and topic. */
export function suggestCoverPrompt(bookId: string, body: SuggestCoverPromptRequest): Promise<SuggestCoverPromptResponse> {
  return request<SuggestCoverPromptResponse>(`/api/books/${bookId}/cover/suggest-prompt`, { method: 'POST', body })
}

/** Start a background task that generates a book's cover art with AI and returns its task id. */
export function generateCover(bookId: string, body: GenerateCoverRequest): Promise<CoverGenerationTask> {
  return request<CoverGenerationTask>(`/api/books/${bookId}/cover/generate`, { method: 'POST', body })
}

/** Replace a book's cover with an uploaded image. */
export function uploadCover(bookId: string, body: UploadCoverRequest): Promise<{ ok: true }> {
  return request<{ ok: true }>(`/api/books/${bookId}/cover/upload`, { method: 'POST', body })
}

/** Remove a book's cover. */
export function deleteCover(bookId: string): Promise<{ ok: true }> {
  return request<{ ok: true }>(`/api/books/${bookId}/cover`, { method: 'DELETE' })
}
