#!/usr/bin/env tsx
/**
 * Builds e2e/fixtures/sample-book.epub, the fixture the epub-import journey
 * (e2e/journeys/epub-import.spec.ts) feeds through the real file-import UI.
 *
 * The fixture is generated by this committed script rather than checked in
 * from an unknown source, because a binary nobody can regenerate or diff is
 * a black box. Anyone who opens this repo can read exactly what produced
 * the fixture, confirm it still matches SAMPLE_BOOK_TITLE and
 * SAMPLE_BOOK_CHAPTERS in e2e/fixtures/sample-book.ts, and regenerate it on
 * demand instead of trusting bytes someone else committed once.
 *
 * It uses epub-gen-memory directly, the same library
 * server/adapters/epub-gen-export.ts wraps for real EPUB exports, so the
 * fixture is a real, valid EPUB zip that the real epub2 parser
 * (server/adapters/epub2-import.ts) can read, not a hand-rolled stand-in.
 *
 * epub-gen-memory ships as CJS with __esModule set, so a dynamic import()
 * of it under Node's ESM loader can yield a double-wrapped default.
 * server/adapters/epub-gen-export.ts documents and handles both shapes; the
 * handling below copies that verbatim rather than importing the adapter, so
 * this script has no dependency on server/.
 *
 * Run with: pnpm e2e:fixture:epub
 */
import { writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { SAMPLE_BOOK_CHAPTERS, SAMPLE_BOOK_TITLE } from '../e2e/fixtures/sample-book.js'

type EpubGenFn = (
  options: Record<string, unknown>,
  content: Array<{ title: string; content: string }>,
) => Promise<Buffer>

async function resolveEpubGenFn(): Promise<EpubGenFn> {
  const epubMod = (await import('epub-gen-memory')) as { default: unknown }
  // epub-gen-memory is CJS with __esModule — handle double-default. Copied
  // from server/adapters/epub-gen-export.ts, which is load-bearing for the
  // Electron production build and must not be simplified away there.
  const epubDefault = epubMod.default as Record<string, unknown>
  return (typeof epubDefault === 'function' ? epubDefault : epubDefault.default) as EpubGenFn
}

async function main(): Promise<void> {
  const epub = await resolveEpubGenFn()

  const options = {
    title: SAMPLE_BOOK_TITLE,
    author: 'Tutor E2E Fixtures',
    numberChaptersInTOC: false,
    prependChapterTitles: false,
  }
  const content = SAMPLE_BOOK_CHAPTERS.map(chapter => ({
    title: chapter.title,
    content: `<p>${chapter.body}</p>`,
  }))

  const buffer = await epub(options, content)

  const outPath = fileURLToPath(new URL('../e2e/fixtures/sample-book.epub', import.meta.url))
  await writeFile(outPath, buffer)
  console.log(`[e2e] wrote ${outPath} (${buffer.length} bytes)`)
}

main().catch((err) => {
  console.error('Failed to build the EPUB fixture:', err)
  process.exit(1)
})
